version: '3.8'

services:
  python-app:
    build: .
    volumes:
      - ./src:/app  # ローカルのディレクトリをマウント
    stdin_open: true  # 標準入力をオープンにする
    tty: true         # 仮想端末を使用
    command: /bin/sh  # シェルを起動